CuriBio/k8s_curi

- core/lib/jobs/jobs/__init__.py
- core/lib/jobs/jobs/jobs.py
- core/lib/utils/utils/db.py
- deployments/pulse3d/services/pulse3d/src/main.py
At some point it probably will make sense to move all the routes for uploads/jobs to their own api probably under apiv2 deployment
> pulse3d jobs

- bin/psql_proxy/Dockerfile
- docker-compose.yml
- frontend/pulse3d/src/.env.development
start db port-forward container
> add docker image for psql port-forwarding, update docker-compose to

- cluster/manifests/ci/base/ci_build_workflow.yaml
@luciipak Not sure if it needs sha or base-sha
> add params for ci-terraform-apply workflowtemplate

- deployments/apiv2/services/users/src/models/users.py
- deployments/apiv2/services/users/tests/test_main.py
- frontend/pulse3d/src/components/admin/NewUserForm.js
> Username special chars

- frontend/pulse3d/src/components/account/LoginForm.js
- frontend/pulse3d/src/components/layouts/ControlPanel.js
- frontend/pulse3d/src/components/layouts/DashboardLayout.js
- frontend/pulse3d/src/components/layouts/Layout.js
- frontend/pulse3d/src/components/uploads/TableRow.js
- frontend/pulse3d/src/pages/_app.js
- frontend/pulse3d/src/pages/login.js
- frontend/pulse3d/src/pages/uploads.js
- frontend/pulse3d/src/serviceWorker.js
Hopefully this fixed all the remaining logout / auth / page routing issues
> Refactor auth checking

- deployments/apiv2/services/users/src/main.py
- deployments/apiv2/services/users/src/models/users.py
- deployments/apiv2/services/users/tests/test_main.py
- deployments/pulse3d/services/pulse3d/src/main.py
- frontend/pulse3d/src/components/admin/UsersRow.js
- frontend/pulse3d/src/components/basicWidgets/ModalWidget.js
- frontend/pulse3d/src/components/layouts/ControlPanel.js
- frontend/pulse3d/src/package-lock.json
- frontend/pulse3d/src/pages/_app.js
- frontend/pulse3d/src/pages/users-info.js
- frontend/pulse3d/src/serviceWorker.js
-Added 3 new routes to users service
1) fetching all users to display on the FE (/users)
2) deleting one user at a time (/user-actions)
3) deactivating one user at a time(/user-actions)
-Added a new route on the FE (/users-info)
> added admin page to view and edit users

- frontend/pulse3d/src/.env.production
- frontend/pulse3d/src/components/uploadForm/AnalysisParamForm.js
- frontend/pulse3d/src/components/uploads/WaveformGraph.js
- frontend/pulse3d/src/pages/upload-form.js
- frontend/pulse3d/src/pages/uploads.js
- remove single download modal
- swapped y-axis normalization to use CheckboxWidget, not checkbox-type form
- swapped y-axis interactive analysis zoom functionality
> Misc fixes

- docker-compose.yml
- frontend/pulse3d/src/components/admin/NewUserForm.js
- frontend/pulse3d/src/components/basicWidgets/FormInput.js
- input box highlighting if and when passwords match
- `Password` changed to `Confirm password`
- Tooltip next to first `Password` label that explains password requirements
> new user form updates

- core/db/curibio/alembic/versions/5d220341bf80_pulse3d_0_27_1.py
- jobs/manifests/base/pulse3d-job.yaml
- jobs/manifests/overlays/prod/kustomization.yaml
- jobs/pulse3d/pulse3d-worker/Makefile
- jobs/pulse3d/pulse3d-worker/src/requirements.txt
Added version 0.27.1 of pulse3D
> added 0.27.1 pulse3d

- frontend/pulse3d/src/pages/uploads.js
- frontend/pulse3d/src/pages/users-info.js
Uploads filter won't reset on each load.
Fixed date filtering.
> fixed filters

- frontend/pulse3d/src/pages/upload-form.js
- frontend/pulse3d/src/pages/users-info.js
Error message  in /uploads-form
> added file names to error message

- frontend/pulse3d/src/components/table/ResizableColumn.js
- frontend/pulse3d/src/pages/uploads.js
Draggable column widths in uploads table.
> Draggable table

- frontend/pulse3d/src/components/table/ResizableColumn.js
- frontend/pulse3d/src/pages/uploads.js
Fixed column filtering/ checkbox logic and draggable response.
> changed branch to RC10272022

- deployments/pulse3d/services/pulse3d/src/main.py
- frontend/pulse3d/src/package-lock.json
- frontend/pulse3d/src/package.json
bumped version of FE to match s3
> Json fe bump

- deployments/pulse3d/services/pulse3d/src/main.py
Added prefix checking when getting parquet file from s3
> S3 parquet

- deployments/pulse3d/manifests/base/pulse3d-dep.yaml
- deployments/pulse3d/manifests/overlays/prod/kustomization.yaml
- deployments/pulse3d/manifests/overlays/test/kustomization.yaml
> first change

- frontend/pulse3d/src/components/basicWidgets/ModalWidget.js
- frontend/pulse3d/src/components/uploads/InteractiveAnalysisModal.js
- frontend/pulse3d/src/components/uploads/WaveformGraph.js
Added a a check before interactive analysis can be submitted for duplicate peaks or valleys
> added modal

- frontend/pulse3d/src/components/interactiveAnalysis/InteractiveAnalysisModal.js
- frontend/pulse3d/src/components/interactiveAnalysis/WaveformGraph.js
- frontend/pulse3d/src/package.json
- Fixed styling of legend component
- Fixed filtering of duplicate peaks and valleys in IA
https://user-images.githubusercontent.com/46114925/235511717-afc9cfa9-9818-4487-862a-95654c04d91c.mp4
> IA style/filter fixes

- frontend/pulse3d/src/components/basicWidgets/DropDownWidget.js
- frontend/pulse3d/src/components/basicWidgets/InputDropdownWidget.js
- frontend/pulse3d/src/components/layouts/DashboardLayout.js
- frontend/pulse3d/src/pages/_app.js
- frontend/pulse3d/src/pages/account-settings.js
- frontend/pulse3d/src/pages/upload-form.js
- frontend/pulse3d/src/pages/uploads.js
- Fixed bug where realoding page would not show files in drop down.
- Added dropdown option in uploads table for re-analysis 
https://user-images.githubusercontent.com/46114925/236006857-168a57fb-b745-454a-a585-6e9e68ff31d8.mp4
> added optional default file

- deployments/apiv2/manifests/overlays/prod/kustomization.yaml
- deployments/apiv2/manifests/overlays/test/kustomization.yaml
- deployments/apiv2/services/mantarray/Makefile
- deployments/apiv2/services/mantarray/src/core/config.py
Bumping the mantarray service and pushing to AWS before QC
> apiv2 mantarray version bump

- frontend/pulse3d/src/components/interactiveAnalysis/InteractiveAnalysisModal.js
- frontend/pulse3d/src/components/interactiveAnalysis/WaveformGraph.js
Fix endpoints being allowed to be dragged outside of graph bounds
Fix windowed analysis elements
Fix issue with dragging peak/valley line when sloped
Fix filtering with sloped line
> Misc IA Fixes

- core/terraform/aurora_rds/main.tf
Passes:
- multi-az by spinning up second instance
- deletion protection
- enhanced monitoring
- cloudwatch
additionally bump version of rds module
> RDS enhanced monitoring

- frontend/pulse3d/src/components/basicWidgets/InputDropdownWidget.js
- frontend/pulse3d/src/components/layouts/Layout.js
- frontend/pulse3d/src/package.json
- frontend/pulse3d/src/pages/_app.js
- frontend/pulse3d/src/pages/upload-form.js
- frontend/pulse3d/src/pages/uploads.js
- frontend/pulse3d/src/serviceWorker.js
- check token expiration when accessing dashboard instead of if token is null
- hard reset upload form and disable dropdown when processing submission
> Misc updates

- deployments/pulse3d/services/pulse3d/src/main.py
- deployments/pulse3d/services/pulse3d/src/models/models.py
- deployments/pulse3d/services/pulse3d/src/requirements.txt
- frontend/pulse3d/src/components/interactiveAnalysis/InteractiveAnalysisModal.js
- frontend/pulse3d/src/components/interactiveAnalysis/JobPreviewModal.js
- frontend/pulse3d/src/components/interactiveAnalysis/useWaveformData.js
- frontend/pulse3d/src/components/uploadForm/AnalysisParamForm.js
- frontend/pulse3d/src/pages/upload-form.js
- frontend/pulse3d/src/pages/uploads.js
- frontend/pulse3d/src/utils/generic.js
- jobs/pulse3d/test-pulse3d-worker/Makefile
- jobs/pulse3d/test-pulse3d-worker/src/main.py
- jobs/pulse3d/test-pulse3d-worker/src/requirements.txt
- jobs/queue-processor/src/main.py
- Add option to disable detrending of nautilai data
- IA + Windowing/Normalization fixes
> Pulse3d Fixes

- frontend/pulse3d/src/components/uploadForm/AnalysisParamForm.js
- frontend/pulse3d/src/components/uploadForm/WellGroups.js
- frontend/pulse3d/src/utils/generic.js
Also add support for well names of 96 and 384 well plates
> Fix issue changing well group title with valid well selection

- deployments/apiv2/services/users/src/main.py
- deployments/apiv2/services/users/src/models/users.py
- deployments/apiv2/services/users/src/templates/registration_sso.html
- deployments/apiv2/services/users/tests/test_main.py
- frontend/pulse3d/src/components/admin/NewAccountForm.js
Hey guys,
I'm adding the ability for curi:admin to create admins with the selected login_type
Please let me know what you guys think. Thanks!
> Allow creation of admins with login_type = sso

- deployments/apiv2/services/users/src/main.py
- deployments/apiv2/services/users/tests/test_main.py
Hey guys,
As discussed, this changes User creation so that Users "inherit" the login_type from the Customer.
Please let me know what you guys think. Thanks!
---
- https://app.asana.com/0/0/1207435942363894
> Create users with their Customer's login_type

- deployments/apiv2/services/users/src/main.py
- deployments/apiv2/services/users/tests/test_main.py
- frontend/pulse3d/src/pages/login.js
Hey guys,
I'm adding the 'Sign in with Microsoft' option to our User sign-in page.
Please let me know if you have any questions, comments, or suggestions.
Thanks!
Roberto
---
- https://app.asana.com/0/0/1207463773246277
> Allow users to 'Sign in with Microsoft'

- core/lib/auth/auth/__init__.py
- core/lib/auth/auth/models.py
- core/lib/auth/auth/tokens.py
- deployments/apiv2/services/users/src/main.py
- deployments/apiv2/services/users/tests/test_main.py
- frontend/pulse3d/src/components/admin/NewAccountForm.js
- frontend/pulse3d/src/pages/_app.js
- frontend/pulse3d/src/serviceWorker.js
Hey guys,
As discussed, I'm adding LoginType to the tokens so we can use it to selectively display UI components based on it.  I used LoginType to determine the message to display after user creation (see screenshots below), and I'm planning similar changes soon, e.g. hide the "Change Password" functionality for SSO users.
Please let me know what you think.  Thanks!
> Surface LoginType to FE

- core/lib/jobs/jobs/jobs.py
- deployments/apiv2/manifests/overlays/modl/kustomization.yaml
- deployments/apiv2/manifests/overlays/prod/kustomization.yaml
- deployments/apiv2/manifests/overlays/test/kustomization.yaml
- deployments/apiv2/services/users/Makefile
- deployments/apiv2/services/users/src/core/config.py
- deployments/pulse3d/manifests/overlays/modl/kustomization.yaml
- deployments/pulse3d/manifests/overlays/prod/kustomization.yaml
- deployments/pulse3d/manifests/overlays/test/kustomization.yaml
- deployments/pulse3d/services/pulse3d/Makefile
- deployments/pulse3d/services/pulse3d/src/core/config.py
Hey guys,
This fixes the issue where `get_customer_quota` gets `total_jobs:None`, tries to cast to int, and blows up.
I think this is the right branch to PR against, but please let me know if I missed something.  Thanks!
> Fix get_customer_quota to handle total_jobs:None

- deployments/apiv2/services/users/src/main.py
- deployments/apiv2/services/users/tests/test_main.py
---
- https://app.asana.com/0/0/1207591552834327
> Change sso_admin to also check sso_organization and sso_admin_org_id

- core/db/curibio/alembic/versions/c8c266af4275_adduserorgidtousers.py
- deployments/apiv2/services/users/src/main.py
- deployments/apiv2/services/users/tests/test_main.py
---
- https://app.asana.com/0/0/1207591552834331
> Change sso_user to also check sso_organization and sso_user_org_id

- frontend/pulse3d/src/components/interactiveAnalysis/InteractiveAnalysisModal.js
- frontend/pulse3d/src/components/interactiveAnalysis/InteractiveWaveformGraph.js
> IA clean up + Remove dups for single well

- deployments/apiv2/services/users/src/main.py
- frontend/pulse3d/src/pages/user-info.js
---
- https://app.asana.com/0/0/1207623190596033
> Tweak user info for SSO customers

- frontend/pulse3d/src/pages/uploads.js
---
- https://app.asana.com/0/0/1207544419800121
> Resize columns in the uploads section

- core/lib/jobs/jobs/jobs.py
---
- https://app.asana.com/0/0/1207739769323706
> Make uploads date filter inclusive

- frontend/pulse3d/src/pages/uploads.js
---
- https://app.asana.com/0/0/1207739769323710
> Add tooltip to uploads date filters

- frontend/pulse3d/src/components/table/Jobs.js
- frontend/pulse3d/src/pages/uploads.js
- frontend/pulse3d/src/utils/jsx.js
---
- https://app.asana.com/0/0/1207651868417759
> Show Job ID in subtable

- frontend/pulse3d/src/pages/login.js
---
- https://app.asana.com/0/0/1207670210192649
> Show better SSO error message when button is clicked twice

- frontend/pulse3d/src/pages/uploads.js
> Remove date filter UTC tooltip

- frontend/pulse3d/src/pages/login.js
---
- https://app.asana.com/0/0/1207870444595812
> Display SSO errors separately

- core/db/curibio/alembic/versions/9566734eccae_remove_metadata_from_notify_payloads.py
- jobs/pulse3d/pulse3d-worker/src/main.py
- jobs/queue-processor/src/main.py
Also:
- fix p3d output upload location
- remove metadata from pg_notify calls
> P3d worker store metrics output

- frontend/pulse3d/src/components/editor/Editor.js
- frontend/pulse3d/src/components/layouts/ControlPanel.js
- frontend/pulse3d/src/package-lock.json
- frontend/pulse3d/src/package.json
- frontend/pulse3d/src/pages/_app.js
- frontend/pulse3d/src/pages/notifications-management.js
---
- https://app.asana.com/0/0/1208036956191063
> Display basic Quill editor

- deployments/pulse3d/services/pulse3d/Dockerfile
- deployments/pulse3d/services/pulse3d/src/main.py
- deployments/pulse3d/services/pulse3d/src/models/models.py
- deployments/pulse3d/services/pulse3d/src/repository/notification_repository.py
- deployments/pulse3d/services/pulse3d/src/service/notification_service.py
- deployments/pulse3d/services/pulse3d/tests/conftest.py
---
- https://app.asana.com/0/0/1208065885903026
> Add save_notification endpoint

- frontend/pulse3d/src/pages/login.js
- frontend/pulse3d/src/pages/notifications-management.js
---
- https://app.asana.com/0/0/1208150013879247
> Notifications front-end response handling

- deployments/pulse3d/services/pulse3d/src/main.py
- deployments/pulse3d/services/pulse3d/src/models/models.py
- deployments/pulse3d/services/pulse3d/src/repository/notification_repository.py
- deployments/pulse3d/services/pulse3d/src/service/notification_service.py
- frontend/pulse3d/src/components/table/Table.js
- frontend/pulse3d/src/pages/notifications-management.js
- frontend/pulse3d/src/utils/jsx.js
Adding endpoint to retrieve all notifications
Displaying notifications list
Displaying notification detail
Fix UUID tooltip so it doesn't wrap
---
- https://app.asana.com/0/0/1208065885903028
- https://app.asana.com/0/0/1208065885903029
> Show curi admin notification list and details

- frontend/pulse3d/src/package-lock.json
- frontend/pulse3d/src/package.json
- frontend/pulse3d/src/pages/notifications-management.js
---
- https://app.asana.com/0/0/1208297454463093
> Add dompurify to curi admin notification detail view

- core/db/curibio/alembic/versions/a869e370f0c7_createnotificationmessagestable.py
---
- https://app.asana.com/0/0/1208324797316745
> Create notification_messages table

- frontend/pulse3d/src/pages/notifications-management.js
---
- https://app.asana.com/0/0/1208364891463385
> Add Notification Preview

- deployments/pulse3d/services/pulse3d/src/repository/notification_repository.py
---
- https://app.asana.com/0/0/1208439184335048
> Change notification endpoint to also create per-[user|customer] notification messages

- core/db/curibio/alembic/versions/f6fc3ccd01e2_notificationmessagesnotifytrigger.py
---
- https://app.asana.com/0/0/1208442213650612
> Add DB trigger on notification_messages table to notify of INSERTs

- deployments/apiv2/services/event-broker/src/main.py
- frontend/pulse3d/src/utils/eventSource.js
Notified both curi-admin:
and another user:
---
- https://app.asana.com/0/0/1208459965688282
> Send notification_update from event-broker to eventSource

- frontend/pulse3d/src/components/editor/BundledTinyMCEEditor.js
- frontend/pulse3d/src/components/layouts/ControlPanel.js
- frontend/pulse3d/src/components/layouts/DashboardLayout.js
- frontend/pulse3d/src/components/layouts/Layout.js
- frontend/pulse3d/src/pages/_app.js
- frontend/pulse3d/src/pages/notification-messages.js
- frontend/pulse3d/src/utils/generic.js
---
- https://app.asana.com/0/0/1208525150634773
> Show notification messages to customers and users

- frontend/pulse3d/src/components/layouts/Layout.js
- frontend/pulse3d/src/pages/_app.js
- frontend/pulse3d/src/utils/eventSource.js
Tested locally and the badge number goes up and down as expected when messages are curi-admin-created and audience-read.
---
- https://app.asana.com/0/0/1208531337873148
> Use eventSource to update notificationMessages

- deployments/pulse3d/services/pulse3d/src/main.py
- deployments/pulse3d/services/pulse3d/src/requirements.txt
- jobs/pulse3d/pulse3d-worker/Makefile
- jobs/pulse3d/pulse3d-worker/src/main.py
- jobs/pulse3d/pulse3d-worker/src/requirements.txt
- Fix platemap override
- Pull in p3d v2.0.0rc5 to fix an issue with the charts
> P3d 2.0.0 fixes

- core/db/curibio/alembic/versions/dbf4f67a6571_p3d_v2_0_1.py
- core/lib/jobs/jobs/jobs.py
- core/lib/jobs/setup.py
- deployments/advanced-analysis/manifests/overlays/modl/kustomization.yaml
- deployments/advanced-analysis/manifests/overlays/prod/kustomization.yaml
- deployments/advanced-analysis/services/advanced-analysis/Makefile
- deployments/advanced-analysis/services/advanced-analysis/src/core/config.py
- deployments/pulse3d/manifests/overlays/modl/kustomization.yaml
- deployments/pulse3d/manifests/overlays/prod/kustomization.yaml
- deployments/pulse3d/manifests/overlays/test/kustomization.yaml
- deployments/pulse3d/services/pulse3d/Makefile
- deployments/pulse3d/services/pulse3d/src/core/config.py
- deployments/pulse3d/services/pulse3d/src/requirements.txt
- jobs/pulse3d/pulse3d-worker/Makefile
- jobs/pulse3d/pulse3d-worker/src/requirements.txt
- P3D v2.0.1
- Fix advanced analysis usage check
> QC P3D v2.0.1

- deployments/apiv2/manifests/overlays/modl/kustomization.yaml
- deployments/apiv2/manifests/overlays/prod/kustomization.yaml
- deployments/apiv2/manifests/overlays/test/kustomization.yaml
- deployments/apiv2/services/users/Makefile
- deployments/apiv2/services/users/src/core/config.py
- deployments/apiv2/services/users/src/main.py
- frontend/pulse3d/src/components/uploadForm/AnalysisParamForm.js
- frontend/pulse3d/src/components/uploadForm/AnalysisWindows.js
- frontend/pulse3d/src/components/uploadForm/PlatemapOverride.js
- frontend/pulse3d/src/package-lock.json
- frontend/pulse3d/src/package.json
- frontend/pulse3d/src/pages/upload-form.js
- Allow selecting multiple analysis windows in upload-form
- Remove analysis credit usage warning when re-analyzing, show static warning message instead explaining how credits are consumed
- Update how timezone is set for scheduler
> Multiple analysis windows + Remove analysis credit usage warning

- core/db/curibio/alembic/versions/d68df89254b4_uploads_multipart_upload_id.py
- core/lib/jobs/jobs/jobs.py
- core/lib/utils/utils/s3.py
- deployments/pulse3d/services/pulse3d/src/main.py
- deployments/pulse3d/services/pulse3d/src/models/models.py
- Add multipart_upload_id col to uploads table
- POST /uploads/multipart
- PUT /uploads/multipart/complete
- PUT /uploads/multipart/abort
> Multipart upload routes

- cluster/manifests/grafana/base/dashboards/p3d-jobs.json
- core/lib/jobs/jobs/jobs.py
- deployments/pulse3d/services/pulse3d/Dockerfile
- docker-compose.yml
- Update DB queries to work with uploads that don't have any jobs run on them
- Fix docker build
- Fix DB queries in grafana dashboard
> Jobless upload support
